# Generated by Django 2.1.7 on 2019-09-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_id', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=45)),
                ('celphone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='Enero', max_length=6)),
                ('status', models.CharField(choices=[('S', 'Solicitado'), ('I', 'Instalado')], default='Solicitado', max_length=20)),
                ('anio', models.IntegerField(default=2019)),
                ('notes', models.CharField(max_length=500)),
                ('num_campaign', models.IntegerField()),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellingsapp.Person')),
            ],
        ),
    ]
