# Generated by Django 2.1.7 on 2019-09-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingsapp', '0002_auto_20190905_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='product_cant',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='product_name',
            field=models.CharField(choices=[('Op', 'One play'), ('Dp', 'Duo play'), ('Tp', 'Triple play')], default='One play', max_length=20),
        ),
    ]
