# Generated by Django 2.2.5 on 2019-09-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingsapp', '0003_auto_20190906_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='Enero', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='product_name',
            field=models.CharField(choices=[('oneplay', 'One play'), ('duoplay', 'Duo play'), ('tripleplay', 'Triple play')], default='One play', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('instalado', 'Instalado')], default='Solicitado', max_length=20),
        ),
    ]
