# Generated by Django 2.1.7 on 2019-10-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingsapp', '0004_auto_20190920_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_ingresada', models.IntegerField(default=0)),
                ('meta_instalada', models.IntegerField(default=0)),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='Enero', max_length=20)),
                ('anio', models.IntegerField(default=2019)),
                ('canal_venta', models.CharField(choices=[('FWD', 'FWD'), ('CU', 'CU')], default='FWD', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='product_name',
            field=models.CharField(choices=[('one', 'One'), ('duoplay', 'Duo play'), ('tripleplay', 'Triple play')], default='One play', max_length=20),
        ),
    ]
