# Generated by Django 2.1.7 on 2019-10-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingsapp', '0005_auto_20191021_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='product_name',
            field=models.CharField(choices=[('one', 'One'), ('duoplay', 'Duo play'), ('tripleplay', 'Triple play')], default='One', max_length=20),
        ),
    ]
