# Generated by Django 2.1.7 on 2019-10-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingsapp', '0006_auto_20191021_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='canal_venta',
            field=models.CharField(choices=[('FVD', 'FVD'), ('CU', 'CU')], default='FWD', max_length=20),
        ),
        migrations.AlterField(
            model_name='metas',
            name='canal_venta',
            field=models.CharField(choices=[('FVD', 'FVD'), ('CU', 'CU')], default='FWD', max_length=20),
        ),
    ]
