# Generated by Django 2.1.7 on 2019-10-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingsapp', '0007_auto_20191024_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='canal_venta',
        ),
        migrations.AddField(
            model_name='person',
            name='canal_de_venta',
            field=models.CharField(choices=[('FVD', 'FVD'), ('CU', 'CU')], default='FVD', max_length=20),
        ),
        migrations.AlterField(
            model_name='metas',
            name='canal_venta',
            field=models.CharField(choices=[('FVD', 'FVD'), ('CU', 'CU')], default='FVD', max_length=20),
        ),
    ]
