# Generated by Django 2.1.7 on 2020-01-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingsapp', '0011_auto_20191108_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifas',
            name='canal_venta',
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='nombre_rango',
            field=models.CharField(choices=[('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3'), ('R4', 'R4'), ('R5', 'R5')], default='R1', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='porce_title',
            field=models.CharField(choices=[('0-10%', '0-10%'), ('10-14%', '10-14%'), ('>14%', '>14%'), ('INTER', 'INTER')], default='0-10%', max_length=20),
        ),
    ]
