# Generated by Django 2.1.7 on 2020-01-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingsapp', '0012_auto_20200115_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas',
            name='porce_title',
            field=models.CharField(choices=[('porcentaje_0a10', '0-10%'), ('porcentaje_10a14', '10-14%'), ('porcentaje_m14', '>14%'), ('INTER', 'INTER')], default='0-10%', max_length=20),
        ),
    ]
