# Generated by Django 2.1.7 on 2020-01-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingsapp', '0013_auto_20200117_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
