# Generated by Django 2.1.7 on 2020-02-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingsapp', '0014_feriados'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='celcliente',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nomcliente',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
