# Generated by Django 2.1.7 on 2020-02-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingsapp', '0015_auto_20200204_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='celcliente',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
